# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-03 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='college',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='gamesDrawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='gamesLost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='gamesWon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='mobileNumber',
            field=models.IntegerField(default=0),
        ),
    ]
